# Generated by Django 3.2.15 on 2022-09-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0005_sqllookuptables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookuptablerowowner',
            name='couch_id',
        ),
    ]
